spring.application.name=paiva-backend
server.port=8080

# MongoDB Configuration
# Change this URI if using MongoDB Atlas (e.g., mongodb+srv://<user>:<password>@cluster0.mongodb.net/paiva_db)
spring.data.mongodb.uri=mongodb://localhost:27017/paiva

# JWT Configuration
paiva.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
paiva.app.jwtExpirationMs=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=684113538725-1bkdm6t6gq96i2es8nl5pcb6vl54apu8.apps.googleusercontent.com

# Spring AI Groq Configuration (Using OpenAI Compatible Endpoint)
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=llama-3.1-8b-instant